hubertdang/fire-drone-swarm

README.md
=> Add Squash and Merge to README.md

docs/.$fire_detected_sequence.drawio.bkp, docs/.$fire_drone_swarm_class.drawio.bkp, docs/fire_detected_sequence.drawio, docs/fire_drone_swarm_class.drawio
Fixes # 7
Made a first iteration of UML diagrams. Only the first use case listed in the project specification is shown in the sequence diagram. More will come later.
=> First iteration of UML diagrams with basic sequence.

src/AgentTank.java, src/Drone.java, src/DroneStatus.java, src/FireIncidentSubsystem.java, src/FireSeverity.java, src/MissionQueue.java, src/Position.java, src/Scheduler.java, src/Zone.java
Fixes # 10
Build all the classes and method stubs for future development
=> Make classes and method stubs for the entire system

src/Position.java, src/PositionTest.java
=> position class method definitions + tests

src/MissionQueue.java
Fixes # 27
Changed the data structure of the queue from PriorityQueue to HashMap instead (I found it easier to maintain and I think it may be faster)
Implemented all methods of the MissionQueue class
Added comments
Tests coming soon.
=> 27 implement missionqueue class

src/Scheduler.java
Fixes #13 
- Implemented all class methods except run() [waiting on new changes to drone and fireIncidentSubsystem classes that deal with setting flags]
- comparePriority() method still outstanding [to be done soon]
Tests are coming soon.
=> implement scheduler class

README.md
Added project structure, how to set up and run the code and breakdown of contributions. 
=> Updated Readme with requirements needed for iteration

.idea/uiDesigner.xml, src/AgentTank.java, src/AgentTankTest.java, src/Drone.java, src/DroneBuffer.java, src/DroneStatus.java, src/FireIncidentBuffer.java, src/FireIncidentSubsystem.java, src/FireIncidentSubsystemTest.java, src/FireSeverity.java, src/Main.java, src/MissionQueue.java, src/PositionTest.java, src/Scheduler.java, src/SimEvent.java, src/Task.java, src/TimeUtils.java, src/Zone.java, src/ZoneTest.java
Fixes #(37)
NOT COMPLETE
Created communication buffers to mediate message passing between the FireIncidentSubsystem, Scheduler, and Drone.
Developed main simulation sequence as a proof of concept, for component validation.
Refactored codebase to account for structural changes needed to perform message passing.
=> 37 implement box buffer communication

src/DroneBufferTest.java, src/FireIncidentBufferTest.java
=> Adding tests for buffers

src/Drone.java, src/DroneTest.java
=> added Drone unit Test

README.md, src/AgentTankTest.java, src/FireIncidentSubsystemTest.java, src/SimEventTest.java
Updated readme and fixed some failing tests
- [] Bug fix
=> Updated readme and fixed some failing tests

src/MissionQueue.java, src/MissionQueueTest.java, src/Scheduler.java, src/SchedulerTest.java
Added tests for both scheduler and mission queue classes
=> Tests for Scheduler and MissionQueue classes

README.md
Added the docs for UML in the project structure and added Missionqueuetest in breakdown
=> Added docs for UML

src/Drone.java, src/FireIncidentSubsystem.java, src/SimEventTest.java
=> updated logs w/ emojis

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, FireDroneSwarm.iml, src/AgentTank.java, src/Drone.java, src/DroneBuffer.java, src/DroneBufferTest.java, src/DroneTest.java, src/FireIncidentBufferTest.java, src/FireIncidentSubsystem.java, src/Main.java, src/MissionQueue.java, src/MissionQueueTest.java, src/Position.java, src/Scheduler.java, src/SchedulerTest.java, src/SimEvent.java, src/SimEventTest.java
Fixes # 44
New formatter that I think you guys will like. ALSO. IF THE CODE YOU WORK ON HAS LINES GOING OVER 100 COLUMNS (the vertical line has been newly adjusted to be at 100 cols) PLEASE CONTINUE THE STATEMENT ON THE NEXT LINE.
=> new format!!!!!!!!!!!!!

src/Position.java
=> Added a toString method

.idea/misc.xml, src/DroneActionsTable.java, src/HappyPathSubState.java, src/RerouteSubState.java, src/ResupplySubState.java, src/SchedulerSubState.java
Fixes # 67
Created Drone Actions table and scheduler substates
=> Implementing drone actions table and sched substates

src/Drone.java, src/DroneActionsTable.java, src/DroneManager.java, src/FireIncidentSubsystem.java, src/Main.java, src/Scheduler.java, tests/DroneTest.java
- Add check for newTaskFlag in states to account for an external event.
- Removed debugging logs
Note: Wasn't sure how to test this, going to ask in discord
=> Add functionality to leave current state + remove test logs

tests/DroneTest.java
Fixes #86 
Added Drone state machine tests
Tests how the states change based on events. Each tests triggers necessary events required for a state change. 
Questions: 
- I'm using print statements for testing state changes as I couldn't find a way to test the drone in each state. This is because one event calls a function which calls another event so I couldn't find a way to break that flow. Looking for ideas if this can be done in a different way.
- Are tests for functions like fly(), releaseAgent() needed? The state machine tests implicitly test this (since states won't change if these functions are not working correctly) but I wasn't sure if tests for these functions are needed. 
All unit …
=> 86 update unit testing for scheduler and drone state machine

src/Decelerating.java, src/Drone.java, src/DroneController.java, src/DroneManager.java, src/DroneSubsystem.java, src/DroneTaskType.java, src/Landing.java, src/Main.java, src/MessagePasser.java, src/ReleasingAgent.java, src/Scheduler.java
Fixes # 102
* new `DroneSubsystem.java` class that simply contains the `main()` to run the drone-related threads from
* `Drone.java` refactored to send/receive requests to the scheduler for new tasks (like when it arrives at a zone) via UDP
* `DroneController.java` class that handles input from the scheduler (when the scheduler initiates communication, so all the cases where Drone and Scheduler communicate, excluding what is covered by `Drone.java`). This class should effectively replace `DroneManager.java`, which can be removed once this is fully implemented
* My assumption is that scheduler is on /172.17.57.52:6000, it's hardcoded and scheduler can provide an interface to get this info later
* I've left sending back acknowledgements up to @AmileshN . Currently, in the `processTask()` …
=> Implement UDP for the drone subsystem and refactoring

src/DroneInfo.java, src/DroneTask.java, src/Position.java, src/Zone.java, tests/SchedulerTest.java
* added implement Serializable to Zone, Position,  DroneInfo, DroneTask
=> 108 implement serializable to necessary classes

.idea/misc.xml, src/Drone.java, src/DroneActionsTable.java, src/DroneController.java, src/DroneInfo.java, src/DroneRequestHandler.java, src/DroneSubsystem.java, src/FireEventHandler.java, src/FireIncidentSubsystem.java, src/Main.java, src/Scheduler.java, src/SchedulerSubsystem.java, tests/DroneTest.java, tests/FireIncidentSubsystemTest.java
Fixes # 103
* Added UDP communication between Drone and Scheduler (added just the send part of FIS to Scheduler for testing changes)
* Created two new threads, FireEventHandler and DroneRequestHandler
* FireEventHandler class is designed to handle fire events and schedule drones to respond to these events. It initializes with a port number and a reference to the Scheduler
* DroneRequestHandler is responsible for handling requests related to drone operations. It initializes with a port number and a reference to the Scheduler
* Scheduler is now a shared resource used by the two threads above to schedule, not an active object anymore
* Currently, the number of drones is hardcoded in a for loop. Each drone is assumed to have a unique ID starting from 1. The system uses a convention where the …
=> UDP for scheduler

src/DroneActionsTable.java, src/DroneRequestHandler.java, src/FireIncidentSubsystem.java, src/Main.java, src/MessagePasser.java, src/Scheduler.java, tests/SchedulerTest.java
#104 
Implemented FireIncidentSubsystem UDP.
Fixed scheduler bug.
=> 104 implement udp message passing for fire incident subsystem

src/Scheduler.java, tests/DroneBufferTest.java, tests/FireIncidentBufferTest.java, tests/SchedulerTest.java
* list
* your
* changes
* here
=> Updated schedulerTest

src/DroneInfo.java, src/DroneRequestHandler.java, src/FireEventHandler.java, src/MessagePasser.java, src/Scheduler.java
Fixes # (117)
Implemented scheduler fault handling.
=> 117 scheduler drone fault detection

tests/DroneSubsystemTest.java
* added a unit test for DroneSubsystem
=> added a DroneSubsystemTest

src/Drone.java, tests/DroneTest.java
=> drone fault test

src/Drone.java, src/FireIncidentSubsystem.java, src/TimeUtils.java, src/ZoneTriageInfo.java
* list
* your
* changes
* here
=> Speeding up time for iter5
